// Built-in backup list for the brainstorm helper, used only if Deezer can't be
// reached. Normally the helper browses Deezer's live charts and playlists.
//
// Song row:  [title, artist, year, genre, tags]
// Album row: [title, artist, year, genre, tags]
//   tags  p party · s sing-along · l love songs · c chill · f feel-good
//         w workout · r road trip · e explicit
// Rows are roughly in order of how well known they are.

const SONGS = [
  ['Bohemian Rhapsody', 'Queen', 1975, 'Rock', 's'],
  ['Billie Jean', 'Michael Jackson', 1982, 'Pop', 'ps'],
  ["Don't Stop Believin'", 'Journey', 1981, 'Rock', 'sr'],
  ['Hey Jude', 'The Beatles', 1968, 'Rock', 's'],
  ['Dancing Queen', 'ABBA', 1976, 'Pop', 'psf'],
  ['Blinding Lights', 'The Weeknd', 2019, 'Pop', 'pwr'],
  ['Shake It Off', 'Taylor Swift', 2014, 'Pop', 'psf'],
  ['Uptown Funk', 'Mark Ronson', 2014, 'Pop', 'pf'],
  ['I Wanna Dance with Somebody', 'Whitney Houston', 1987, 'Pop', 'psf'],
  ["Livin' on a Prayer", 'Bon Jovi', 1986, 'Rock', 'ps'],
  ['Sweet Child O\' Mine', "Guns N' Roses", 1987, 'Rock', 'r'],
  ['Smells Like Teen Spirit', 'Nirvana', 1991, 'Alternative', ''],
  ['Mr. Brightside', 'The Killers', 2004, 'Alternative', 'sp'],
  ['September', 'Earth, Wind & Fire', 1978, 'Soul & Funk', 'pfs'],
  ['Hotel California', 'Eagles', 1976, 'Rock', 'r'],
  ['Thriller', 'Michael Jackson', 1982, 'Pop', 'p'],
  ['Beat It', 'Michael Jackson', 1982, 'Pop', 'w'],
  ['Rolling in the Deep', 'Adele', 2010, 'Pop', 's'],
  ['Someone Like You', 'Adele', 2011, 'Pop', 'ls'],
  ['Shape of You', 'Ed Sheeran', 2017, 'Pop', ''],
  ['Perfect', 'Ed Sheeran', 2017, 'Pop', 'l'],
  ['Thinking Out Loud', 'Ed Sheeran', 2014, 'Pop', 'l'],
  ['Happy', 'Pharrell Williams', 2013, 'Pop', 'f'],
  ['Bad Guy', 'Billie Eilish', 2019, 'Pop', ''],
  ['Birds of a Feather', 'Billie Eilish', 2024, 'Pop', 'l'],
  ['Levitating', 'Dua Lipa', 2020, 'Pop', 'p'],
  ["Don't Start Now", 'Dua Lipa', 2019, 'Pop', 'p'],
  ['As It Was', 'Harry Styles', 2022, 'Pop', 'r'],
  ['Watermelon Sugar', 'Harry Styles', 2019, 'Pop', 'f'],
  ['Flowers', 'Miley Cyrus', 2023, 'Pop', 'f'],
  ['Party in the U.S.A.', 'Miley Cyrus', 2009, 'Pop', 'ps'],
  ['drivers license', 'Olivia Rodrigo', 2021, 'Pop', ''],
  ['Espresso', 'Sabrina Carpenter', 2024, 'Pop', 'p'],
  ['Anti-Hero', 'Taylor Swift', 2022, 'Pop', 's'],
  ['Cruel Summer', 'Taylor Swift', 2019, 'Pop', ''],
  ['Love Story', 'Taylor Swift', 2008, 'Pop', 'ls'],
  ['Crazy in Love', 'Beyoncé', 2003, 'R&B', 'p'],
  ['Halo', 'Beyoncé', 2008, 'Pop', 'l'],
  ['Single Ladies (Put a Ring on It)', 'Beyoncé', 2008, 'R&B', 'p'],
  ['Texas Hold \'Em', 'Beyoncé', 2024, 'Country', 'p'],
  ['Umbrella', 'Rihanna', 2007, 'Pop', 's'],
  ['Toxic', 'Britney Spears', 2003, 'Pop', 'p'],
  ['...Baby One More Time', 'Britney Spears', 1998, 'Pop', 's'],
  ['Wannabe', 'Spice Girls', 1996, 'Pop', 'ps'],
  ['Since U Been Gone', 'Kelly Clarkson', 2004, 'Pop', 's'],
  ['Call Me Maybe', 'Carly Rae Jepsen', 2012, 'Pop', 'ps'],
  ['Firework', 'Katy Perry', 2010, 'Pop', 's'],
  ['Poker Face', 'Lady Gaga', 2008, 'Pop', 'p'],
  ['Bad Romance', 'Lady Gaga', 2009, 'Pop', 'p'],
  ['Shallow', 'Lady Gaga & Bradley Cooper', 2018, 'Pop', 'ls'],
  ['Die With A Smile', 'Lady Gaga & Bruno Mars', 2024, 'Pop', 'l'],
  ['APT.', 'ROSÉ & Bruno Mars', 2024, 'Pop', 'p'],
  ['Good Luck, Babe!', 'Chappell Roan', 2024, 'Pop', ''],
  ['Girls Just Want to Have Fun', 'Cyndi Lauper', 1983, 'Pop', 'psf'],
  ['Like a Prayer', 'Madonna', 1989, 'Pop', 's'],
  ['I Will Always Love You', 'Whitney Houston', 1992, 'Pop', 'l'],
  ['My Heart Will Go On', 'Céline Dion', 1997, 'Pop', 'ls'],
  ['Take On Me', 'a-ha', 1985, 'Pop', 'sr'],
  ['Everybody Wants to Rule the World', 'Tears for Fears', 1985, 'Pop', 'r'],
  ['Sweet Dreams (Are Made of This)', 'Eurythmics', 1983, 'Pop', ''],
  ['Total Eclipse of the Heart', 'Bonnie Tyler', 1983, 'Pop', 's'],
  ['Walking on Sunshine', 'Katrina and the Waves', 1985, 'Pop', 'f'],
  ['Mamma Mia', 'ABBA', 1975, 'Pop', 's'],
  ['I Gotta Feeling', 'The Black Eyed Peas', 2009, 'Pop', 'pf'],
  ["Can't Stop the Feeling!", 'Justin Timberlake', 2016, 'Pop', 'pf'],
  ['SexyBack', 'Justin Timberlake', 2006, 'Pop', 'p'],
  ['Sorry', 'Justin Bieber', 2015, 'Pop', ''],
  ['Royals', 'Lorde', 2013, 'Pop', ''],
  ['Dynamite', 'BTS', 2020, 'Pop', 'pf'],
  ['Gangnam Style', 'PSY', 2012, 'Pop', 'p'],
  ['Havana', 'Camila Cabello', 2017, 'Pop', ''],
  ['Circles', 'Post Malone', 2019, 'Pop', ''],
  ['Golden Hour', 'JVKE', 2022, 'Pop', 'l'],
  ['Kiss from a Rose', 'Seal', 1994, 'Pop', 'l'],
  ["Can't Help Falling in Love", 'Elvis Presley', 1961, 'Pop', 'l'],
  ['Good Vibrations', 'The Beach Boys', 1966, 'Pop', 'f'],
  ["Wouldn't It Be Nice", 'The Beach Boys', 1966, 'Pop', 'f'],
  ['Sweet Caroline', 'Neil Diamond', 1969, 'Pop', 's'],
  ['Piano Man', 'Billy Joel', 1973, 'Pop', 's'],
  ['Tiny Dancer', 'Elton John', 1971, 'Pop', 'sr'],
  ['Your Song', 'Elton John', 1970, 'Pop', 'l'],
  ['Rocket Man', 'Elton John', 1972, 'Pop', ''],
  ['When Doves Cry', 'Prince', 1984, 'Pop', ''],
  ['Purple Rain', 'Prince', 1984, 'Rock', 'l'],
  ["Don't Stop Me Now", 'Queen', 1978, 'Rock', 'fr'],
  ['We Will Rock You', 'Queen', 1977, 'Rock', 'w'],
  ['Another One Bites the Dust', 'Queen', 1980, 'Rock', ''],
  ['Stairway to Heaven', 'Led Zeppelin', 1971, 'Rock', ''],
  ['Wonderwall', 'Oasis', 1995, 'Rock', 's'],
  ['Back in Black', 'AC/DC', 1980, 'Rock', 'w'],
  ['Thunderstruck', 'AC/DC', 1990, 'Rock', 'w'],
  ['Highway to Hell', 'AC/DC', 1979, 'Rock', 'r'],
  ['Eye of the Tiger', 'Survivor', 1982, 'Rock', 'w'],
  ['Born to Run', 'Bruce Springsteen', 1975, 'Rock', 'r'],
  ['Born in the U.S.A.', 'Bruce Springsteen', 1984, 'Rock', ''],
  ['Let It Be', 'The Beatles', 1970, 'Rock', 'c'],
  ['Here Comes the Sun', 'The Beatles', 1969, 'Rock', 'fc'],
  ['Twist and Shout', 'The Beatles', 1963, 'Rock', 'ps'],
  ['Yesterday', 'The Beatles', 1965, 'Rock', 'c'],
  ["(I Can't Get No) Satisfaction", 'The Rolling Stones', 1965, 'Rock', ''],
  ['Paint It Black', 'The Rolling Stones', 1966, 'Rock', ''],
  ['Imagine', 'John Lennon', 1971, 'Rock', 'c'],
  ['Like a Rolling Stone', 'Bob Dylan', 1965, 'Rock', ''],
  ['Africa', 'Toto', 1982, 'Rock', 'sr'],
  ['Mr. Blue Sky', 'Electric Light Orchestra', 1977, 'Rock', 'fr'],
  ['Dreams', 'Fleetwood Mac', 1977, 'Rock', 'c'],
  ['Go Your Own Way', 'Fleetwood Mac', 1977, 'Rock', 'r'],
  ["Free Fallin'", 'Tom Petty', 1989, 'Rock', 'r'],
  ['Brown Eyed Girl', 'Van Morrison', 1967, 'Rock', 'fr'],
  ["Don't You (Forget About Me)", 'Simple Minds', 1985, 'Rock', ''],
  ['Footloose', 'Kenny Loggins', 1984, 'Rock', 'p'],
  ['Danger Zone', 'Kenny Loggins', 1986, 'Rock', 'r'],
  ['Johnny B. Goode', 'Chuck Berry', 1958, 'Rock', 'p'],
  ['Jailhouse Rock', 'Elvis Presley', 1957, 'Rock', 'p'],
  ['Hound Dog', 'Elvis Presley', 1956, 'Rock', ''],
  ['Seven Nation Army', 'The White Stripes', 2003, 'Alternative', 'w'],
  ['Losing My Religion', 'R.E.M.', 1991, 'Alternative', ''],
  ['Zombie', 'The Cranberries', 1994, 'Alternative', ''],
  ['Creep', 'Radiohead', 1992, 'Alternative', 'e'],
  ['Take Me Out', 'Franz Ferdinand', 2004, 'Alternative', ''],
  ['Somebody That I Used to Know', 'Gotye', 2011, 'Alternative', ''],
  ['Pumped Up Kicks', 'Foster the People', 2010, 'Alternative', ''],
  ['Do I Wanna Know?', 'Arctic Monkeys', 2013, 'Alternative', ''],
  ['Feel Good Inc.', 'Gorillaz', 2005, 'Alternative', ''],
  ['Yellow', 'Coldplay', 2000, 'Alternative', 'lc'],
  ['Clocks', 'Coldplay', 2002, 'Alternative', 'c'],
  ['Viva la Vida', 'Coldplay', 2008, 'Alternative', 's'],
  ['Under the Bridge', 'Red Hot Chili Peppers', 1991, 'Alternative', ''],
  ['Believer', 'Imagine Dragons', 2017, 'Alternative', 'w'],
  ['Radioactive', 'Imagine Dragons', 2012, 'Alternative', 'w'],
  ['Heat Waves', 'Glass Animals', 2020, 'Alternative', 'c'],
  ['Superstition', 'Stevie Wonder', 1972, 'Soul & Funk', 'pf'],
  ['Sir Duke', 'Stevie Wonder', 1976, 'Soul & Funk', 'f'],
  ['Respect', 'Aretha Franklin', 1967, 'Soul & Funk', 's'],
  ["Ain't No Mountain High Enough", 'Marvin Gaye & Tammi Terrell', 1967, 'Soul & Funk', 'fr'],
  ["What's Going On", 'Marvin Gaye', 1971, 'Soul & Funk', 'c'],
  ["Let's Stay Together", 'Al Green', 1971, 'Soul & Funk', 'l'],
  ['Stand by Me', 'Ben E. King', 1961, 'Soul & Funk', 'lc'],
  ['My Girl', 'The Temptations', 1964, 'Soul & Funk', 'lf'],
  ['I Want You Back', 'The Jackson 5', 1969, 'Soul & Funk', 'fp'],
  ['Shout', 'The Isley Brothers', 1959, 'Soul & Funk', 'p'],
  ["Stayin' Alive", 'Bee Gees', 1977, 'Dance', 'p'],
  ['I Will Survive', 'Gloria Gaynor', 1978, 'Dance', 'ps'],
  ['Le Freak', 'Chic', 1978, 'Dance', 'p'],
  ['Get Lucky', 'Daft Punk', 2013, 'Dance', 'p'],
  ['One More Time', 'Daft Punk', 2000, 'Dance', 'p'],
  ['Around the World', 'Daft Punk', 1997, 'Dance', ''],
  ['Titanium', 'David Guetta', 2011, 'Dance', 'w'],
  ['Wake Me Up', 'Avicii', 2013, 'Dance', 'rf'],
  ['Levels', 'Avicii', 2011, 'Dance', 'p'],
  ['Sandstorm', 'Darude', 1999, 'Dance', 'wp'],
  ['Blue (Da Ba Dee)', 'Eiffel 65', 1998, 'Dance', 'ps'],
  ['Animals', 'Martin Garrix', 2013, 'Dance', 'w'],
  ["Don't You Worry Child", 'Swedish House Mafia', 2012, 'Dance', 's'],
  ['Lean On', 'Major Lazer & DJ Snake', 2015, 'Dance', 'p'],
  ['One Kiss', 'Calvin Harris & Dua Lipa', 2018, 'Dance', 'p'],
  ['No Scrubs', 'TLC', 1999, 'R&B', 's'],
  ['Waterfalls', 'TLC', 1995, 'R&B', ''],
  ['Say My Name', "Destiny's Child", 1999, 'R&B', ''],
  ['Yeah!', 'Usher', 2004, 'R&B', 'p'],
  ['No Diggity', 'Blackstreet', 1996, 'R&B', ''],
  ['All of Me', 'John Legend', 2013, 'R&B', 'l'],
  ['Kill Bill', 'SZA', 2022, 'R&B', 'e'],
  ['Hey Ya!', 'OutKast', 2003, 'Rap/Hip Hop', 'pf'],
  ['Ms. Jackson', 'OutKast', 2000, 'Rap/Hip Hop', 'e'],
  ['Hotline Bling', 'Drake', 2015, 'Rap/Hip Hop', ''],
  ["God's Plan", 'Drake', 2018, 'Rap/Hip Hop', ''],
  ['Lose Yourself', 'Eminem', 2002, 'Rap/Hip Hop', 'we'],
  ['Without Me', 'Eminem', 2002, 'Rap/Hip Hop', 'e'],
  ['Juicy', 'The Notorious B.I.G.', 1994, 'Rap/Hip Hop', 'e'],
  ['California Love', '2Pac', 1995, 'Rap/Hip Hop', 'pe'],
  ['Gin and Juice', 'Snoop Dogg', 1994, 'Rap/Hip Hop', 'e'],
  ['In Da Club', '50 Cent', 2003, 'Rap/Hip Hop', 'pe'],
  ['Empire State of Mind', 'Jay-Z', 2009, 'Rap/Hip Hop', 'e'],
  ['HUMBLE.', 'Kendrick Lamar', 2017, 'Rap/Hip Hop', 'e'],
  ['Not Like Us', 'Kendrick Lamar', 2024, 'Rap/Hip Hop', 'e'],
  ['SICKO MODE', 'Travis Scott', 2018, 'Rap/Hip Hop', 'e'],
  ['Sunflower', 'Post Malone & Swae Lee', 2018, 'Rap/Hip Hop', 'c'],
  ["Rapper's Delight", 'The Sugarhill Gang', 1979, 'Rap/Hip Hop', 'p'],
  ['Ice Ice Baby', 'Vanilla Ice', 1990, 'Rap/Hip Hop', 'ps'],
  ['Jump Around', 'House of Pain', 1992, 'Rap/Hip Hop', 'pe'],
  ["Can't Hold Us", 'Macklemore & Ryan Lewis', 2012, 'Rap/Hip Hop', 'w'],
  ['Old Town Road', 'Lil Nas X', 2019, 'Country', 'sf'],
  ['Friends in Low Places', 'Garth Brooks', 1990, 'Country', 's'],
  ['Jolene', 'Dolly Parton', 1973, 'Country', ''],
  ['9 to 5', 'Dolly Parton', 1980, 'Country', 'sf'],
  ['Take Me Home, Country Roads', 'John Denver', 1971, 'Country', 'sr'],
  ['Ring of Fire', 'Johnny Cash', 1963, 'Country', ''],
  ['Man! I Feel Like a Woman!', 'Shania Twain', 1997, 'Country', 'ps'],
  ['Before He Cheats', 'Carrie Underwood', 2006, 'Country', 's'],
  ['Tennessee Whiskey', 'Chris Stapleton', 2015, 'Country', 'c'],
  ['Wagon Wheel', 'Darius Rucker', 2013, 'Country', 'sr'],
  ['The Gambler', 'Kenny Rogers', 1978, 'Country', ''],
  ['Last Night', 'Morgan Wallen', 2023, 'Country', ''],
  ['Despacito', 'Luis Fonsi', 2017, 'Latin Music', 'p'],
  ['Gasolina', 'Daddy Yankee', 2004, 'Latin Music', 'p'],
  ['Hips Don\'t Lie', 'Shakira', 2006, 'Latin Music', 'p'],
  ['Waka Waka (This Time for Africa)', 'Shakira', 2010, 'Latin Music', 'p'],
  ['Bailando', 'Enrique Iglesias', 2014, 'Latin Music', 'p'],
  ['Mi Gente', 'J Balvin', 2017, 'Latin Music', 'p'],
  ['Tití Me Preguntó', 'Bad Bunny', 2022, 'Latin Music', 'e'],
  ['La Bamba', 'Ritchie Valens', 1958, 'Latin Music', 'p'],
  ["Livin' la Vida Loca", 'Ricky Martin', 1999, 'Latin Music', 'p'],
  ['Three Little Birds', 'Bob Marley & The Wailers', 1977, 'Reggae', 'fc'],
  ['One Love', 'Bob Marley & The Wailers', 1977, 'Reggae', 'c'],
  ['Is This Love', 'Bob Marley & The Wailers', 1978, 'Reggae', 'l'],
  ['Red Red Wine', 'UB40', 1983, 'Reggae', ''],
  ['What a Wonderful World', 'Louis Armstrong', 1967, 'Jazz', 'c'],
  ['Fly Me to the Moon', 'Frank Sinatra', 1964, 'Jazz', 'l'],
  ['Take Five', 'The Dave Brubeck Quartet', 1959, 'Jazz', 'c'],
  ['Feeling Good', 'Nina Simone', 1965, 'Jazz', ''],
  ['So What', 'Miles Davis', 1959, 'Jazz', 'c'],
  ['Enter Sandman', 'Metallica', 1991, 'Metal', 'w'],
  ['Master of Puppets', 'Metallica', 1986, 'Metal', ''],
  ['Paranoid', 'Black Sabbath', 1970, 'Metal', ''],
  ['Crazy Train', 'Ozzy Osbourne', 1980, 'Metal', 'w'],
  ['Chop Suey!', 'System of a Down', 2001, 'Metal', ''],
  ['The Trooper', 'Iron Maiden', 1983, 'Metal', ''],
  ['Fast Car', 'Tracy Chapman', 1988, 'Folk', 'rc'],
  ['Riptide', 'Vance Joy', 2013, 'Folk', 'r'],
  ['Ho Hey', 'The Lumineers', 2012, 'Folk', 's'],
  ['Little Talks', 'Of Monsters and Men', 2011, 'Folk', ''],
  ['Hallelujah', 'Jeff Buckley', 1994, 'Folk', 'c'],
  ['The Sound of Silence', 'Simon & Garfunkel', 1965, 'Folk', 'c'],
  ["Blowin' in the Wind", 'Bob Dylan', 1963, 'Folk', ''],
  ['The Thrill Is Gone', 'B.B. King', 1969, 'Blues', ''],
  ['Pride and Joy', 'Stevie Ray Vaughan', 1983, 'Blues', ''],
  ['Let It Go', 'Idina Menzel', 2013, 'Films/Games', 's'],
  ["We Don't Talk About Bruno", 'Encanto Cast', 2021, 'Films/Games', 's'],
  ["How Far I'll Go", "Auli'i Cravalho", 2016, 'Films/Games', 's'],
  ["You're Welcome", 'Dwayne Johnson', 2016, 'Films/Games', 's'],
  ['Under the Sea', 'Samuel E. Wright', 1989, 'Films/Games', 's'],
  ['A Whole New World', 'Brad Kane & Lea Salonga', 1992, 'Films/Games', 'l'],
  ['Ghostbusters', 'Ray Parker Jr.', 1984, 'Films/Games', 'p'],
  ["(I've Had) The Time of My Life", 'Bill Medley & Jennifer Warnes', 1987, 'Films/Games', 'l'],
];

const ALBUMS = [
  ['Thriller', 'Michael Jackson', 1982, 'Pop', ''],
  ['Abbey Road', 'The Beatles', 1969, 'Rock', ''],
  ['Rumours', 'Fleetwood Mac', 1977, 'Rock', ''],
  ['The Dark Side of the Moon', 'Pink Floyd', 1973, 'Rock', ''],
  ['Back in Black', 'AC/DC', 1980, 'Rock', ''],
  ['21', 'Adele', 2011, 'Pop', ''],
  ['1989', 'Taylor Swift', 2014, 'Pop', ''],
  ['Nevermind', 'Nirvana', 1991, 'Alternative', ''],
  ['Hotel California', 'Eagles', 1976, 'Rock', ''],
  ['A Night at the Opera', 'Queen', 1975, 'Rock', ''],
  ['Purple Rain', 'Prince', 1984, 'Pop', ''],
  ["Sgt. Pepper's Lonely Hearts Club Band", 'The Beatles', 1967, 'Rock', ''],
  ['Led Zeppelin IV', 'Led Zeppelin', 1971, 'Rock', ''],
  ['Born to Run', 'Bruce Springsteen', 1975, 'Rock', ''],
  ['Born in the U.S.A.', 'Bruce Springsteen', 1984, 'Rock', ''],
  ['Appetite for Destruction', "Guns N' Roses", 1987, 'Rock', 'e'],
  ['The Joshua Tree', 'U2', 1987, 'Rock', ''],
  ['OK Computer', 'Radiohead', 1997, 'Alternative', ''],
  ['Songs in the Key of Life', 'Stevie Wonder', 1976, 'Soul & Funk', ''],
  ["What's Going On", 'Marvin Gaye', 1971, 'Soul & Funk', ''],
  ['Back to Black', 'Amy Winehouse', 2006, 'Soul & Funk', 'e'],
  ['Kind of Blue', 'Miles Davis', 1959, 'Jazz', ''],
  ['Come Away with Me', 'Norah Jones', 2002, 'Jazz', ''],
  ['Legend', 'Bob Marley & The Wailers', 1984, 'Reggae', ''],
  ['folklore', 'Taylor Swift', 2020, 'Pop', ''],
  ['Midnights', 'Taylor Swift', 2022, 'Pop', ''],
  ['Lemonade', 'Beyoncé', 2016, 'R&B', 'e'],
  ['Renaissance', 'Beyoncé', 2022, 'Dance', 'e'],
  ['The Miseducation of Lauryn Hill', 'Lauryn Hill', 1998, 'R&B', 'e'],
  ['good kid, m.A.A.d city', 'Kendrick Lamar', 2012, 'Rap/Hip Hop', 'e'],
  ['To Pimp a Butterfly', 'Kendrick Lamar', 2015, 'Rap/Hip Hop', 'e'],
  ['The Marshall Mathers LP', 'Eminem', 2000, 'Rap/Hip Hop', 'e'],
  ['Illmatic', 'Nas', 1994, 'Rap/Hip Hop', 'e'],
  ['Ready to Die', 'The Notorious B.I.G.', 1994, 'Rap/Hip Hop', 'e'],
  ['My Beautiful Dark Twisted Fantasy', 'Kanye West', 2010, 'Rap/Hip Hop', 'e'],
  ['Take Care', 'Drake', 2011, 'Rap/Hip Hop', 'e'],
  ['Random Access Memories', 'Daft Punk', 2013, 'Dance', ''],
  ['Discovery', 'Daft Punk', 2001, 'Dance', ''],
  ['Future Nostalgia', 'Dua Lipa', 2020, 'Pop', ''],
  ['Fine Line', 'Harry Styles', 2019, 'Pop', ''],
  ["Harry's House", 'Harry Styles', 2022, 'Pop', ''],
  ['When We All Fall Asleep, Where Do We Go?', 'Billie Eilish', 2019, 'Pop', ''],
  ['SOUR', 'Olivia Rodrigo', 2021, 'Pop', 'e'],
  ['After Hours', 'The Weeknd', 2020, 'Pop', 'e'],
  ['Jagged Little Pill', 'Alanis Morissette', 1995, 'Alternative', 'e'],
  ['Bad', 'Michael Jackson', 1987, 'Pop', ''],
  ['Off the Wall', 'Michael Jackson', 1979, 'Pop', ''],
  ['Like a Prayer', 'Madonna', 1989, 'Pop', ''],
  ['Tapestry', 'Carole King', 1971, 'Pop', ''],
  ['Pet Sounds', 'The Beach Boys', 1966, 'Pop', ''],
  ['Blue', 'Joni Mitchell', 1971, 'Folk', ''],
  ['Highway 61 Revisited', 'Bob Dylan', 1965, 'Folk', ''],
  ['Golden Hour', 'Kacey Musgraves', 2018, 'Country', ''],
  ['Come On Over', 'Shania Twain', 1997, 'Country', ''],
  ['No Fences', 'Garth Brooks', 1990, 'Country', ''],
  ['Jolene', 'Dolly Parton', 1974, 'Country', ''],
  ['Un Verano Sin Ti', 'Bad Bunny', 2022, 'Latin Music', 'e'],
  ['Master of Puppets', 'Metallica', 1986, 'Metal', ''],
  ['Metallica', 'Metallica', 1991, 'Metal', ''],
  ['Paranoid', 'Black Sabbath', 1970, 'Metal', ''],
  ['Parachutes', 'Coldplay', 2000, 'Alternative', ''],
  ['A Rush of Blood to the Head', 'Coldplay', 2002, 'Alternative', ''],
  ['AM', 'Arctic Monkeys', 2013, 'Alternative', ''],
  ['Hot Fuss', 'The Killers', 2004, 'Alternative', ''],
  ['Is This It', 'The Strokes', 2001, 'Alternative', ''],
  ['The Bodyguard', 'Whitney Houston', 1992, 'Films/Games', ''],
  ['Saturday Night Fever', 'Bee Gees', 1977, 'Films/Games', ''],
];

const toRow = (kind) => ([title, artist, year, genre, tags = ''], i) => ({
  kind,
  title,
  artist,
  year,
  genre,
  tags,
  explicit: tags.includes('e'),
  rank: i,
});

export const SONG_CATALOG = SONGS.map(toRow('song'));
export const ALBUM_CATALOG = ALBUMS.map(toRow('album'));

// Artists come from the songs and albums above, most famous first.
export const ARTIST_CATALOG = (() => {
  const seen = new Map();
  for (const row of [...SONG_CATALOG, ...ALBUM_CATALOG]) {
    for (const name of row.artist.split(/\s+&\s+/)) {
      if (name === 'Encanto Cast' || seen.has(name)) continue;
      seen.set(name, { kind: 'artist', title: name, artist: null, year: null, genre: row.genre, tags: row.tags.replace('e', ''), explicit: false, rank: seen.size });
    }
  }
  return [...seen.values()];
})();

export const CATALOG_GENRES = [...new Set(SONG_CATALOG.map((r) => r.genre))].sort();
